### ISSUE TITLE
Exception during execution: ".ctor" with "4" argument(s): "

### ISSUE THREAD

**Issue by stephan-koch** [DungKHoang/Generate-ansible-playbook-from-powershell#1]
downloaded the repo and tried it but getting below error:

Create Ansible Playbook  -->     ov-addresspoolsubnet.yml
Create Ansible Playbook  -->     ov-timelocale.yml
New-Object : Exception calling ".ctor" with "4" argument(s): "The value 1.0.9(I) is not a semantic version format.
Parameter name: version"
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.420\4.20.2133.3186\HPOneView.420.psm1:28074 char:30
+ ... tsList.Add((New-Object HPOneView.Appliance.Baseline+FwComponent($_Com ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : Exception calling ".ctor" with "4" argument(s): "The value 1.0.9(I) is not a semantic version format.
Parameter name: version"
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.420\4.20.2133.3186\HPOneView.420.psm1:28074 char:30
+ ... tsList.Add((New-Object HPOneView.Appliance.Baseline+FwComponent($_Com ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

POSH-OneView 4.20.2133.3186
POSH VErsion Table
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  858

**Comment by DungKHoang** [comment]
Hi Stephan
It seems that the cmdlet Get-HPOVBaseline produces an error in with POSH 4.20. 
The script works fine in POSH 4.10
I open an issue against POSH 4.20

Thanks!
/Dung
